services:

  # ============================================================
  # STREAM PIPELINE
  # ============================================================
  stream-pipeline:
    build: .
    container_name: stream-pipeline

    environment:
      PIPELINE_RUNTIME_SECONDS: "30"
      PIPELINE_ROWS_PER_SECOND: "5"

      PYSPARK_PYTHON: python3
      PYSPARK_DRIVER_PYTHON: python3

      PYTHONPATH: /opt/stream-pipeline/src:/opt/stream-pipeline
      PIPELINE_BASE_DIR: /opt/stream-pipeline

      # ========================================================
      # MINIO
      # Comunicação entre containers
      # ========================================================
      MINIO_ENDPOINT: http://host.docker.internal:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_BUCKET: stream-pipeline

      # ========================================================
      # POSTGRESQL
      # ========================================================
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: "5432"
      POSTGRES_DB: vehicle_financing
      POSTGRES_USER: dw_user
      POSTGRES_PASSWORD: dw_password

    volumes:
      - ./data:/opt/stream-pipeline/data

    extra_hosts:
      - "host.docker.internal:host-gateway"

    depends_on:
      minio:
        condition: service_healthy

      minio-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy

    ports:
      - "4040:4040"

    command:
      [
        "/opt/spark/bin/spark-submit",
        "--master",
        "local[2]",
        "/opt/stream-pipeline/src/medallion_pipeline.py"
      ]


  # ============================================================
  # TESTS
  # ============================================================
  tests:
    build: .

    container_name: stream-pipeline-tests

    environment:
      PYTHONPATH: /opt/stream-pipeline/src:/opt/stream-pipeline
      PYSPARK_PYTHON: python3
      PYSPARK_DRIVER_PYTHON: python3

    command:
      [
        "python3",
        "-m",
        "pytest",
        "-q"
      ]

    volumes:
      - ./data:/opt/stream-pipeline/data


  # ============================================================
  # MINIO
  # ============================================================
  minio:
    image: quay.io/minio/minio:latest

    command:
      - server
      - /data
      - --address
      - "0.0.0.0:9000"
      - --console-address
      - "0.0.0.0:9001"

    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123

    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - minio_data:/data

    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      start_period: 15s
      interval: 5s
      timeout: 5s
      retries: 30


    # ============================================================
  # MINIO INITIALIZATION
  # ============================================================
  minio-init:
    image: quay.io/minio/mc:latest

    extra_hosts:
      - "host.docker.internal:host-gateway"

    depends_on:
      minio:
        condition: service_healthy

    entrypoint:
      - /bin/sh
      - -c
      - |
        set -e

        echo "=========================================="
        echo "Inicializando MinIO"
        echo "=========================================="

        echo "Configurando alias do MinIO..."

        mc alias set \
          local \
          http://host.docker.internal:9000 \
          minio \
          minio123 \
          --api S3v4

        echo "Alias configurado com sucesso."

        echo "Criando/verificando bucket..."

        mc mb \
          --ignore-existing \
          local/stream-pipeline

        echo "=========================================="
        echo "Bucket stream-pipeline pronto!"
        echo "=========================================="


  # ============================================================
  # POSTGRES
  # ============================================================
  postgres:
    image: postgres:16
    container_name: stream-pipeline-postgres

    environment:
      POSTGRES_DB: vehicle_financing
      POSTGRES_USER: dw_user
      POSTGRES_PASSWORD: dw_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U dw_user -d vehicle_financing"
        ]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 10


# ==============================================================
# VOLUMES
# ==============================================================
volumes:
  minio_data:
  postgres_data: